
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
const SET_USER_PHOTOS = 'SET_USER_PHOTOS'
const SET_POSTS = 'SET_POSTS'
const SET_NEW_POST = 'SET_NEW_POST'
const INIT_NEW_POST = 'INIT_NEW_POST'
const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
const SET_CART = 'SET_CART'

export {
  SET_CURRENT_USER,
  SET_ACCESS_TOKEN,
  SET_USER_PHOTOS,
  SET_POSTS,
  SET_NEW_POST,
  INIT_NEW_POST,
  SET_LOADING_STATUS,
  SET_CART,
};
